# Generated by Django 2.2.16 on 2020-11-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Titile of page')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=100, verbose_name='New title')),
                ('new_text', models.TextField(verbose_name='New text')),
                ('new_pub_date', models.DateTimeField(verbose_name='Date of publish')),
                ('new_photo', models.ImageField(upload_to='', verbose_name='Image of new')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Title')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='Data')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Title')),
            ],
        ),
    ]
