# Generated by Django 2.2.16 on 2020-11-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201112_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='new_photo',
            new_name='new_image',
        ),
    ]
