# Generated by Django 2.2.16 on 2020-11-27 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_postcareer_postcontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostContacts',
            new_name='PostContact',
        ),
    ]
