# Generated by Django 2.2.16 on 2020-11-27 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201127_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 33, 23, 337774, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AddField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 33, 23, 336088, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 33, 23, 293642, tzinfo=utc), verbose_name='Date of publish'),
        ),
    ]
