# Generated by Django 2.2.16 on 2020-11-27 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201128_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 21, 17, 26, 734412, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 21, 17, 26, 771655, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 21, 17, 26, 769780, tzinfo=utc), verbose_name='Date of publish'),
        ),
    ]
