# Generated by Django 2.2.16 on 2020-12-01 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201128_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d', verbose_name='NEW_IMAGE'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 10, 51, 15, 338790, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Patronymic'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 13, 51, 15, 363483)),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 13, 51, 15, 362381)),
        ),
    ]
