# Generated by Django 2.2.16 on 2020-12-01 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201201_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image of field'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 11, 4, 39, 350859, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 14, 4, 39, 374120)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 14, 4, 39, 373031)),
        ),
    ]
