# Generated by Django 2.2.16 on 2020-12-04 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201201_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image of field2'),
        ),
        migrations.AddField(
            model_name='new',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image of field3'),
        ),
        migrations.AddField(
            model_name='new',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='new',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='new',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 16, 1, 42, 561685, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(verbose_name='Text4'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 19, 1, 42, 600218)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 19, 1, 42, 599604)),
        ),
    ]
