# Generated by Django 2.2.16 on 2020-12-04 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201204_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Text2'),
        ),
        migrations.AddField(
            model_name='new',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Text3'),
        ),
        migrations.AddField(
            model_name='new',
            name='text4',
            field=models.TextField(blank=True, verbose_name='Text4'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 16, 11, 28, 924563, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 19, 11, 28, 963129)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 19, 11, 28, 962439)),
        ),
    ]
