# Generated by Django 2.2.16 on 2021-01-04 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201205_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(blank=True, max_length=15, verbose_name='Type of project'),
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 14, 30, 869849, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 14, 30, 907039)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 14, 30, 906496)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 14, 30, 905421, tzinfo=utc), verbose_name='Date of publish'),
        ),
    ]
