# Generated by Django 2.2.16 on 2021-01-04 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210104_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 14, 50, 618911, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 14, 50, 656538)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 14, 50, 655965)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 14, 50, 654895, tzinfo=utc), verbose_name='Date of publish'),
        ),
    ]
