# Generated by Django 2.2.16 on 2021-01-04 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210104_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of project')),
                ('text', models.TextField(verbose_name='Text')),
                ('project_type', models.CharField(blank=True, max_length=15, verbose_name='Type of project')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='MAIN PHOTO')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='VIDEO 3')),
                ('text2', models.TextField(blank=True, verbose_name='Text 2')),
                ('image2', models.ImageField(blank=True, upload_to='images/', verbose_name='ADDITIOANL PHOTO')),
                ('video2', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='VIDEO 2')),
                ('text3', models.TextField(blank=True, verbose_name='Text 3')),
                ('image3', models.ImageField(blank=True, upload_to='images/', verbose_name='ADDITIOANL PHOTO 2')),
                ('video3', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='VIDEO 3')),
                ('text4', models.TextField(blank=True, verbose_name='Text 4')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 16, 16, 821190, tzinfo=utc), verbose_name='Date of publish')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 18, 16, 16, 783975, tzinfo=utc), verbose_name='Date of publish'),
        ),
        migrations.AlterField(
            model_name='postcareer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 16, 16, 823124)),
        ),
        migrations.AlterField(
            model_name='postcontact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 21, 16, 16, 822400)),
        ),
    ]
